version: '3'
services:
    movietown-db:
        container_name: movietown-db
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - "./sql:/docker-entrypoint-initdb.d/"
        networks:
            - apps-network
    movietown-be:
      build:
        context: .
        dockerfile: ./movietown/Dockerfile
      ports:
        - "4000:4000"
      env_file:
        - ./movietown/.env
      depends_on:
        movietown-db:
          condition: service_started
      networks:
        - apps-network

networks:
    apps-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
